// GENERADO por scripts/gen-guia-rutas.mjs en cada build. NO EDITAR A MANO.
// Ruta → nombre actual de la ficha del tablero que lleva a ella.
export const RUTAS_FICHAS: Record<string, string> = {
  "/acudiente/actividades": "Actividades",
  "/acudiente/comunicados": "Comunicados",
  "/acudiente/consultas": "Consultas",
  "/acudiente/documentos": "Documentos",
  "/acudiente/estadisticas": "Estadísticas",
  "/acudiente/notas": "Notas",
  "/aprende-normi": "Aprende con Normi",
  "/asistencia": "Asistencia",
  "/boletines": "Boletines",
  "/calendario-escolar": "Calendario",
  "/comunicados-firma": "Comunicados con firma",
  "/comunicados-recibidos": "Comunicados Recibidos",
  "/construye-institucion": "Configurar Institución",
  "/consultas": "Consultas",
  "/direccion-grupo": "Dirección de grupo",
  "/documentos-recibidos": "Documentos Recibidos",
  "/enviar-comunicado": "Enviar Comunicado",
  "/estadisticas": "Estadísticas",
  "/estudiante/actividades": "Actividades",
  "/estudiante/comunicados": "Comunicados",
  "/estudiante/consultas": "Consultas",
  "/estudiante/documentos": "Documentos",
  "/estudiante/estadisticas": "Estadísticas",
  "/estudiante/notas": "Notas",
  "/formatos": "Formatos",
  "/manual-convivencia": "Manual de Convivencia",
  "/normi-examinadora": "Normi Examinadora",
  "/observador-estudiantil": "Observador Estudiantil",
  "/orientador/casos": "Casos de Seguimiento",
  "/orientador/citas": "Citas y Atención",
  "/orientador/remisiones": "Orientación Escolar",
  "/panel-control": "Panel de Control",
  "/perfil": "Perfil",
  "/permisos-excusas": "Permisos y Excusas",
  "/porteria": "Portería",
  "/profesor/asistencia": "Asistencia",
  "/profesor/comunicados": "Comunicados Recibidos",
  "/profesor/documentos": "Documentos Recibidos",
  "/profesor/estadisticas": "Estadísticas",
  "/profesor/logros": "Logros del periodo",
  "/profesor/programar-actividad": "Actividades",
  "/registro-normi": "Registro en Normi",
  "/registros-comportamiento": "Registros de Comportamiento",
  "/seleccionar-grado": "Notas",
  "/solicitud-entrevista": "Solicitud de Entrevista",
  "/solicitud-entrevista-staff": "Solicitud de Entrevista",
  "/uso-normi": "Uso de Normi",
};
